version: "3.9"

services:
  sensorhub:
    image: ghcr.io/sloretz/ros:humble-desktop
    container_name: ros2-sensorhub
    privileged: true
    network_mode: host
    environment:
      - ROS_DOMAIN_ID=42
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      
      #- FASTRTPS_DEFAULT_PROFILES_FILE=/ros2_ws/config/fastdds.xml
    volumes:
      # - /home/marcio/Documentos/Dev/UEFS/IC/CoppeliaSim_Edu_V4_10_0_rev0_Ubuntu22_04:/coppelia
      # Volumes para usar no pc
      - ${ROS2_WORKSPACE_PATH:-./sensorhub}:/ros2_ws

      # Volumes compartilhados
      - /tmp:/tmp
      - /dev/pts:/dev/pts

      # Volumes para usar na raspberry
      # - ${FASTDDS_CONFIG_PATH}:/ros2_ws/config/fastdds.xml
      # - ${WIRINGPI_PATH}:/ros2_ws/src/wiringpi

      # Mantendo apenas pra verificação posterior
      # - /home/labpds/.ros/fastdds.xml:/ros2_ws/config/fastdds.xml
      # - /home/labpds/Documentos/ros2-sensorhub:/ros2_ws
      # - /home/labpds/WiringPi:/ros2_ws/src/wiringpi
    devices:
      - /dev/mem:/dev/mem
      - /dev/gpiomem:/dev/gpiomem
    tty: true
    stdin_open: true
    command: >
      bash -i -c "
        echo '=== [1/3] Instalando WiringPi ===' &&
        cd /ros2_ws/src/wiringpi/wiringPi &&
        make clean && make && make install &&
        echo '✓ WiringPi instalado com sucesso' &&
        
        echo '=== [2/3] Configurando ROS2 Workspace ===' &&
        source /opt/ros/humble/setup.bash &&
        cd /ros2_ws &&
        source install/setup.bash &&
        echo '✓ ROS2 workspace configurado' &&
        
        echo '=== [3/3] Ambiente pronto ===' &&
        echo 'Execute: ros2 run <pacote> <node>' &&
        echo 'ou compile com: colcon build --symlink-install --executor sequential' &&
        bash
      "
