version: "3.9"

services:
  sensorhub:
    privileged: true
    build:
      context: ..
      dockerfile: dev/Dockerfile
    network_mode: host
    ipc: host
    volumes: 
      - ..:/app/ros2_ws
      - /tmp:/tmp
    env_file: ./.env.pc
    environment:
      - ROS_DOMAIN_ID=42
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - FASTRTPS_DEFAULT_PROFILES_FILE=/app/ros2_ws/dev/fastdds_sensorhub.xml
    
    # apenas na raspberry
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/gpiomem:/dev/gpiomem
    tty: true
    stdin_open: true
    command: >
      bash -c "
        source /opt/ros/humble/setup.bash &&
        bash"

  pc_remoto:
      build: 
        context: ..
        dockerfile: dev/Dockerfile
      network_mode: host
      ipc: host
      volumes: 
        - ..:/app/ros2_ws
      environment:
        - ROS_DOMAIN_ID=42
        - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
        - FASTRTPS_DEFAULT_PROFILES_FILE=/app/ros2_ws/dev/fastdds_remoto.xml
      command: >
        bash -c "
          source /opt/ros/humble/setup.bash &&
          bash"
