version: "3.9"

services:
  sensorhub:
    build:
      context: ..
      dockerfile: dev/Dockerfile
    network_mode: host
    ipc: host
    volumes: 
      - ..:/app/ros2_ws
      - /tmp:/tmp
    env_file: ./.env.pc
    environment:
      - ROS_DOMAIN_ID=42
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - FASTRTPS_DEFAULT_PROFILES_FILE=/app/ros2_ws/dev/fastdds.xml
    #devices:
      #- /dev/gpiomem:/dev/gpiomem
    tty: true
    stdin_open: true
    command: >
      bash -i -c "
        echo '=== [2/2] Ambiente pronto ===' &&
        echo 'Execute: ros2 run <pacote> <node>' &&
        echo 'ou compile com: colcon build --symlink-install --executor sequential' &&
        bash
      "