imu_node:
  ros__parameters:
    update_rate_ms: 15

    imus:
      sensor_1:
        id: 1
        address: 40      # 0x28
        multiplexer: 0
        euler_order: [1, 2, 0]

      sensor_2:
        id: 2
        address: 41      # 0x29
        multiplexer: 1
        euler_order: [1, 2, 0]

      sensor_3:
        id: 3
        address: 40      # 0x28
        multiplexer: 0
        euler_order: [1, 2, 0]
